site_name: 'cat-app'
site_description: 'Main documentation for the cat-app'
repo_url: https://github.com/ricardoandre97/cat-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'